# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: Adam Pash
url:   http://adampash.com
author:
  name:    Adam Pash        # For copyright notice and ATOM feeds
  email:   adam@adampash.com # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - http://login.adampash.com/adam

# Delete the following section if your site will not be acting as an OpenID delegate (http://wiki.openid.net/Delegation)
# If you're deploying with mongrel, make sure you read http://rhnh.net/2008/04/13/nginx-openid-delegation-and-yadis
# open_id_delegation:
# server:   http://ap-openid.herokuapp.com/
# delegate: http://ap-openid.herokuapp.com/adam
